// Generated by components discovery
declare module 'vue' {
  export interface GlobalComponents {
    'CustomButton': typeof import("../../components/CustomButton.vue")['default'],
    'CustomLink': typeof import("../../components/CustomLink.vue")['default'],
    'Modal': typeof import("../../components/Modal.vue")['default'],
    'ModalComponentsAuthModal': typeof import("../../components/ModalComponents/AuthModal.vue")['default'],
    'Todo': typeof import("../../components/TodoList/Todo.vue")['default'],
    'TodoList': typeof import("../../components/TodoList/TodoList.vue")['default'],
    'ChatRoom': typeof import("../../components/Chat/ChatRoomList/ChatRoom.vue")['default'],
    'ChatRoomList': typeof import("../../components/Chat/ChatRoomList/ChatRoomList.vue")['default'],
    'NuxtWelcome': typeof import("../../node_modules/nuxt3/dist/app/components/nuxt-welcome.vue")['default'],
    'ClientOnly': typeof import("../../node_modules/nuxt3/dist/app/components/client-only")['default']
  }
}
export {}
