// Generated by components discovery
declare module 'vue' {
  export interface GlobalComponents {
    'CustomButton': typeof import("../components/CustomButton.vue")['default'],
    'CustomLink': typeof import("../components/CustomLink.vue")['default'],
    'Modal': typeof import("../components/Modal.vue")['default'],
    'ModalComponentsAuthModal': typeof import("../components/ModalComponents/AuthModal.vue")['default'],
    'Todo': typeof import("../components/TodoList/Todo.vue")['default'],
    'TodoList': typeof import("../components/TodoList/TodoList.vue")['default'],
    'ChatRoom': typeof import("../components/Chat/ChatRoomList/ChatRoom.vue")['default'],
    'ChatRoomList': typeof import("../components/Chat/ChatRoomList/ChatRoomList.vue")['default'],
    'NuxtWelcome': typeof import("../node_modules/@nuxt/ui-templates/dist/templates/welcome.vue")['default'],
    'NuxtLayout': typeof import("../node_modules/nuxt/dist/app/components/layout")['default'],
    'NuxtErrorBoundary': typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default'],
    'ClientOnly': typeof import("../node_modules/nuxt/dist/app/components/client-only")['default'],
    'ServerPlaceholder': typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default'],
    'NuxtLink': typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
    'LazyCustomButton': typeof import("../components/CustomButton.vue")['default'],
    'LazyCustomLink': typeof import("../components/CustomLink.vue")['default'],
    'LazyModal': typeof import("../components/Modal.vue")['default'],
    'LazyModalComponentsAuthModal': typeof import("../components/ModalComponents/AuthModal.vue")['default'],
    'LazyTodo': typeof import("../components/TodoList/Todo.vue")['default'],
    'LazyTodoList': typeof import("../components/TodoList/TodoList.vue")['default'],
    'LazyChatRoom': typeof import("../components/Chat/ChatRoomList/ChatRoom.vue")['default'],
    'LazyChatRoomList': typeof import("../components/Chat/ChatRoomList/ChatRoomList.vue")['default'],
    'LazyNuxtWelcome': typeof import("../node_modules/@nuxt/ui-templates/dist/templates/welcome.vue")['default'],
    'LazyNuxtLayout': typeof import("../node_modules/nuxt/dist/app/components/layout")['default'],
    'LazyNuxtErrorBoundary': typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default'],
    'LazyClientOnly': typeof import("../node_modules/nuxt/dist/app/components/client-only")['default'],
    'LazyServerPlaceholder': typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default'],
    'LazyNuxtLink': typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
  }
}
export const CustomButton: typeof import("../components/CustomButton.vue")['default']
export const CustomLink: typeof import("../components/CustomLink.vue")['default']
export const Modal: typeof import("../components/Modal.vue")['default']
export const ModalComponentsAuthModal: typeof import("../components/ModalComponents/AuthModal.vue")['default']
export const Todo: typeof import("../components/TodoList/Todo.vue")['default']
export const TodoList: typeof import("../components/TodoList/TodoList.vue")['default']
export const ChatRoom: typeof import("../components/Chat/ChatRoomList/ChatRoom.vue")['default']
export const ChatRoomList: typeof import("../components/Chat/ChatRoomList/ChatRoomList.vue")['default']
export const NuxtWelcome: typeof import("../node_modules/@nuxt/ui-templates/dist/templates/welcome.vue")['default']
export const NuxtLayout: typeof import("../node_modules/nuxt/dist/app/components/layout")['default']
export const NuxtErrorBoundary: typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
export const ClientOnly: typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']
export const ServerPlaceholder: typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']
export const NuxtLink: typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
export const LazyCustomButton: typeof import("../components/CustomButton.vue")['default']
export const LazyCustomLink: typeof import("../components/CustomLink.vue")['default']
export const LazyModal: typeof import("../components/Modal.vue")['default']
export const LazyModalComponentsAuthModal: typeof import("../components/ModalComponents/AuthModal.vue")['default']
export const LazyTodo: typeof import("../components/TodoList/Todo.vue")['default']
export const LazyTodoList: typeof import("../components/TodoList/TodoList.vue")['default']
export const LazyChatRoom: typeof import("../components/Chat/ChatRoomList/ChatRoom.vue")['default']
export const LazyChatRoomList: typeof import("../components/Chat/ChatRoomList/ChatRoomList.vue")['default']
export const LazyNuxtWelcome: typeof import("../node_modules/@nuxt/ui-templates/dist/templates/welcome.vue")['default']
export const LazyNuxtLayout: typeof import("../node_modules/nuxt/dist/app/components/layout")['default']
export const LazyNuxtErrorBoundary: typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
export const LazyClientOnly: typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']
export const LazyServerPlaceholder: typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']
export const LazyNuxtLink: typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
export const componentNames: string[]
